# Generated by Django 5.2.3 on 2025-06-20 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_alter_conversation_user'),
        ('orders', '0002_alter_order_user'),
        ('users', '0004_remove_user_groups_remove_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
